### ISSUE TITLE
after update to latest image, I get httpd: httpd.conf: No such file or directory  on the docker logs

### ISSUE THREAD

**Issue by user897943** [lipanski/docker-static-website#11]
after update to latest image, I get httpd: httpd.conf: No such file or directory  on the docker logs.

lipanski/docker-static-website:latest
image: sha256:9b08b9509c3284396e7a4def908080160bc87e36fb977e8e2fa9d8217e8152f5
CMD: /busybox httpd -f -v -p 3000 -c httpd.conf
entrypoint: null
env path: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Path: /busybox

**Comment by user897943** [comment]
Also, container does not start obviously

**Comment by lipanski** [comment]
what does your image look like? the default image now creates an empty `httpd.conf` along side your other files. in theory you should have it unless you've changed directories. in that case just add an empty `httpd.conf` or change the `CMD` to drop the `-c httpd.conf`.

**Comment by user897943** [comment]
This is the command I'm using to create the container:

docker create --name=w10iso --restart=always -p 36969:3000 -v /home/xxxx/xxxx/webserver-static/w10:/home/static lipanski/docker-static-website:latest && docker start w10iso

**Comment by user897943** [comment]
I don't build the image, I pull from docker hub... I thought it would handle everything for me? I noticed the change was a move from thttpd to httpd. Before the last change was running flawlessly... Could you implement a change to automate the above suggestion and push to docker hub please? That way we won't need to manually make changes every time.

**Comment by user897943** [comment]
Also, taking the opportunity to thank you for your work in providing this for us.

**Comment by lipanski** [comment]
oh I see what's happening there. when you call `-v /home/xxxx/xxxx/webserver-static/w10:/home/static`, the `/home/static` directory containing the `httpd.conf` gets replaced entirely with your directory.

in that case you either have to add the empty `httpd.conf` file to your directory or change the command to drop the `-c` argument:

```
docker create --name=w10iso --restart=always -p 36969:3000 -v /home/xxxx/xxxx/webserver-static/w10:/home/static lipanski/docker-static-website:latest "/busybox httpd -f -v -p 3000" && docker start w10iso
```

**Comment by user897943** [comment]
Went into the folder, did touch httpd.conf, recreated the container, now it is running again. Thank you!

**Comment by lipanski** [comment]
welcome :+1: an generally if you don't like the changes in 2.1.0, you can always go back to 2.0.0, which doesn't use the `httpd.conf` but it also doesn't provide all the additional goodies that the `httpd.conf` unlocks (see the FAQ section in the README for what I mean).

**Comment by user897943** [comment]
> welcome 👍 an generally if you don't like the changes in 2.1.0, you can always go back to 2.0.0, which doesn't use the `httpd.conf` but it also doesn't provide all the additional goodies that the `httpd.conf` unlocks (see the FAQ section in the README for what I mean).

For my use case, I only need it to serve an iso image of a Windows install disk for PXE to be able to reimage computers from my LAN, so this does the job perfectly, but in the future if I need anything else I will read the docs ;) For now, all is well again. Have a nice day
