### ISSUE TITLE
Hide index.html and .html from url?

### ISSUE THREAD

**Issue by zkvvoob** [lipanski/docker-static-website#13]
Hello,

First of all, thank you very much for putting this image together! So far it works great with my static website. There are only two things that I was hoping I could do:

1. Hide `index.html` and just show the domain name
2. Hide `.html` from all other URLs.

Is this possible? If so, do you know how?

Thanks in advance!

**Comment by zkvvoob** [comment]
Dear @lipanski, will you be able to spare a moment to answer my question below, please?

**Comment by LostOnTheLine** [comment]
Have you actually been able to get it to work as a server? The documentation is so bad I can't figure out how to do even that. I just want to be able to host a single HTML file & can't even do that. It is super stripped down, it cannot even apk once it's built or bin/sh. I'm fairly certain that if you want to do anything extra like that the answer that you won't ever get here is almost certainly "You can't" or rather "If you want to do that you need to add that functionality yourself in the build"

**Comment by lipanski** [comment]
`index.html` should be hidden by default. I think you can hide other `.html` files by placing them inside a directory and renaming them to `index.html`. for example, if you'd like to "alias" `/bla.html` to just `/bla` (or `/bla/` - not sure), you can place that file inside `/bla/index.html`.

if you'd like to know the inner details, you can try and follow the usage of `index_page` in [the busybox httpd source code](https://git.busybox.net/busybox/tree/networking/httpd.c).
