### ISSUE TITLE
request: serve static files from a docker volume

### ISSUE THREAD

**Issue by MrOnak** [lipanski/docker-static-website#17]
I've tried to enable serving of static files from a docker volume (i.e. `--volume ./public:/public_html:ro`) by adding a httpd.conf to my root folder with `H:/public_html` in it). 

I also changed the Dockerfile to include `CMD ["/busybox", "httpd", "-f", "-v", "-p", "3000", "-c", "httpd.conf"]`

For some reason no files get served, all I get is a 404 error. Frankly I have run out of ideas how to test what is wrong.

I'm sure it is an error on my side but would it be possible to have a look into this? It would make changes to content much easier since it wouldn't require a container restart.

[edit to mention change of Dockerfile]

**Comment by lipanski** [comment]
the `WORKDIR` in my Dockerfile is `/home/static` so try and point your volume at that. if you don't have a `httpd.conf` in there, reduce the `CMD` line to `CMD ["/busybox", "httpd", "-f", "-v", "-p", "3000"]` (or add an empty `httpd.conf`.

**Comment by MrOnak** [comment]
Thanks for the fast response! Its a dumb question to ask but are you sure the WORKDIR is `/home/static`?

I tested whether or not my httpd.conf is being used by adding a E404 directive. Turns out I have to put it into the `public` directory of the host, not the base directory. 

Adding the `--volume public:/home/static` and commenting out the `COPY . .` led to all pages being 404'd though.

Then I added `H:/home/static` to the `httpd.conf` as well and the docker container crashes upon start. The error I'm getting is this: `': No such file or directoryan't change directory to '/home/static`

My complete Dockerfile:

    FROM lipanski/docker-static-website:latest
    # Copy your static files
    # COPY public .
    # add httpd.conf file
    CMD ["/busybox", "httpd", "-f", "-v", "-p", "3000", "-c", "httpd.conf"]

I'm building the docker image with these:

    docker build -t busybox_static .
    docker run -d --name teststatic --volume public:/home/static:ro -p 3000:3000 busybox_static
    
Lastly, my httpd.conf

    H:/home/static
    E404:404.html

**Comment by MrOnak** [comment]
Nevermind I believe the issue was my local path while being on windows. It's working as expected.
