### ISSUE TITLE
What's the right way to serve PDF using this Dockerfile

### ISSUE THREAD

**Issue by ashishb** [lipanski/docker-static-website#26]
I have a small website and I love that.
However, I want to serve a PDF file as well.
Right now, the PDF file is not being served with correct mime type causing the browsers to display garbled output.

**Comment by lipanski** [comment]
This is not an issue with the busybox http server itself since I can serve PDF files without an issue. I'd check the file encoding and try to encode the PDFs to UTF8 if possible.
