### ISSUE TITLE
thttpd CGI configuration fails

### ISSUE THREAD

**Issue by johnholliday** [lipanski/docker-static-website#3]
When trying to serve image files, I'm getting 403 errors because of the CGI security setting in THTTPD.  The documentation says it is possible to specify a different CGI_PATTERN from the command line using the '-c' option, which I'm doing as follows:

```
FROM lipanski/docker-static-website:latest

# Copy your static files
COPY . .

CMD ["/thttpd", "-D", "-h", "0.0.0.0", "-p", "3000", "-d", "/home/static", "-u", "static", "-l", "-", "-M", "60", "-c", "\"**.png\"']
```

I've tried different variations of this approach, but nothing works.
I've also gone as far as replacing the "config.h" file prior to thttpd compilation in the base image to #define the CGI_PATTERN directly in the binary image, but nothing seems to work.

**Comment by pushpdeep** [comment]
@lipanski  Thanks for that tip. After struggling for several hours and knowing that it was a file permission issue ( since the http root was getting displayed but not the files) , I gave correct permissions for the data file 
`RUN chmod 644 /var/www/http/index.html`  ( running thttpd with alpine base) 
tried to test a larger static web app deployment, but started to get the 403 error again. I tired adding recursive file and folder permissions but doesn't seems to work. Shall have to do more permission tweaks to get it working.

**Comment by pushpdeep** [comment]
BTW , I decided to use thttpd with `alpine` base after reading [this article](https://www.diva-portal.org/smash/get/diva2:724235/FULLTEXT01.pdf). 

- So I ran a simple one line index.html with both `lighttpd` & `thttpd`  and was surprised to see the results. 
- Container size with `lighttpd` : 4.47 MB & with `thttpd` its 2.7 MB
- in an ideal mode , with no requests coming in, `lighttpd` uses less than 1 MB of RAM
- whereas `thttpd` uses a whooping 160 MB ! 

So I did wanted to make my containers smaller but there is a huge trade-off in terms of Memory ! 

Usage stats : `lightttpd` : 
![Screenshot from 2022-07-10 15-03-36](https://user-images.githubusercontent.com/7886419/178139246-d01aa87c-7709-4837-ab70-60130382d46f.png)

Usage stats : `thttpd` : 

![Screenshot from 2022-07-10 14-51-32](https://user-images.githubusercontent.com/7886419/178139189-c07e9bd6-8f8c-45ca-9e85-8582e0bfde40.png)

**Comment by lipanski** [comment]
@pushpdeep I had my eye on this problem for [a while](https://twitter.com/utopiah/status/1482019200323444744) but couldn't figure out how to contain it.

but I did solve the problem by replacing thttpd with BusyBox httpd instead. the image comes with a significantly lower memory footprint (I'm getting <1MB on my pet projects) and it's actually smaller in size as well (154KB). on top of that, it can do a bunch of other things - check the [FAQ](https://github.com/lipanski/docker-static-website#faq). if you want to give it a try, the transition should be seamless (unless you overwrote the `CMD` line).
