### ISSUE TITLE
File permissions on Windows

### ISSUE THREAD

**Issue by relu91** [lipanski/docker-static-website#4]
I am using the image from a windows machine and I noticed that every file is copied with the executable attribute set to true. This causes thttpd to treat it as a CGI file and therefore it fails to serve even simple HTML pages. Even with the [recently added chmod option](https://github.com/moby/moby/issues/34819) of COPY command is not possible to [correctly copy folders](https://github.com/moby/moby/issues/34819#issuecomment-724077859) inside the container. 

I am leaving this issue to help others that might face the same problem. My workaround is to leverage on an alpine build stage that correctly setups file attributes: 
```
FROM alpine:latest as base

WORKDIR /app

COPY . . 

RUN chmod -R -x+X .

RUN ls -l


FROM lipanski/docker-static-website:latest


COPY --from=base /app .

```

**Comment by lipanski** [comment]
Thanks, I'll add it to the README!

**Comment by lipanski** [comment]
Thanks!
