### ISSUE TITLE
logi

### ISSUE THREAD

**Issue by sp00ck** [lipanski/docker-static-website#6]
Wydaje się, że warto było by gdzieś na zewnatrz kontenera przechowywac logi.
Nawet by zobaczyć czy ktos nie próbuje się włamać.

Druga sprawa to benchmark. Przy uruchomieniu na małym sprzęcie np. raspberry pi zero zasoby nie tylko pamięci ale i cpu mogą byc istotne. 

No i kwestia zwiększenia ilości serwerów (loadbalancing) przy wiekszej ilości maszyn. trzeba jednak zrobić parę kontenerów i zapuścić sprawdzanie wydajności

**Comment by lipanski** [comment]
I don't speak Polish :smiling_face_with_tear: but having passed this through Google Translate I would recommend you to either make a PR to the project (one that keeps the image size small) or, more simple, fork it and tune it to your needs. I am happy with the image as is and it fits my use case but I do accept reasonable changes as PRs.
