### ISSUE TITLE
enable gzip compression

### ISSUE THREAD

**Issue by johnb8005** [lipanski/docker-static-website#7]
I think this project is great!

I was wondering if you were thinking of adding gzip support? (something that I currently do in Nginx but it would be great if it'd work with this project - much smaller docker file size)

**Comment by lipanski** [comment]
afaik thttpd doens't gzip and I doubt they'll add this feature any time soon.

**Comment by lipanski** [comment]
@johnb8005 I just released a new version (2.0.0 or latest) of the image using BusyBox httpd, which comes with gzip support (check the FAQ in the project [README](https://github.com/lipanski/docker-static-website)). You have to provide the gzipped files yourself but it's better than nothing. On top of that, the image is smaller (154KB) and comes with a significantly lower memory footprint than my 1.0.0 version.
